# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77b70214b6415bffe4c8499e0404b2544784baa83ccdb05e17d6075fad81eded43e03be452e57630a55685ae7fdec1bf8a3c3657f88c2f7236fac68409b19424

test:
  secret_key_base: 8e9d460868f9e63e16d4369e39a5c92d849c6216542778525c4c39913fbf9916765fe6d9f3f86553506bed91b4f35ee7ee857c4c523e1063c41be36b3efb4b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
